webclient:
  http_connector:
    auto
  filters:
    context_attributes:
      enabled: true
    cookie_management:
      enabled: true
    retry:
      enabled: true
      retry_options:
        max_attempts: 5
        backoff_factor: 0.5
    logging:
      enabled: true